language: vim

before_script: |
  git clone https://github.com/junegunn/vader.vim.git
  git clone https://github.com/vim/vim.git
  cd vim
  ./configure --with-features=huge
  make
  sudo make install
  cd -

script: |
  /usr/local/bin/vim -Nu <(cat << VIMRC
  set rtp=.
  set rtp+=vader.vim
  set rtp+=/usr/local/share/vim/vim80
  set shiftwidth=4
  VIMRC) -c 'Vader! tests/main.vader'
